allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()  // Ensure this is included
        //maven { url 'https://dl.bintray.com/razorpay/razorpay-android' }  // Add Razorpay's repository if required
    }
}



rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
